title:
  en: "syzygy.ca"
  fr: "syzygy.ca"
description:
  en: "Syzygy.ca -- A computation service making Jupyter notebooks available to Canadian scientists."
  fr: "Syzygy.ca -- Un service de calcul rendant les cahiers de Jupyter accessibles aux scientifiques canadiens."
email: "jupyter@pims.math.ca"
url: "https://syzygy.ca"
author: "Ian Allison"
exclude: ["publish.sh"]
version: 0.0.2

t:
  nav:
    en:
      - name: 'About'
        url: '#about'
      - name: 'Map'
        url: '#gmap-holder'
      - name: 'Partners'
        url: '#partners'
      - name: 'Intro'
        url:  'http://intro.syzygy.ca'
    fr:
      - name: 'À propos'
        url: '#about'
      - name: 'Map'
        url: '#gmap-holder'
      - name: 'Partenaires'
        url: '#partners'
      - name: 'Ouverture de session'
        url: 'http://intro.syzygy.ca'
    button:
      en: 'Launch'
      fr: 'Lancer'
  header:
    heading:
      en: "Launch Jupyter at your university, school or company?"
      fr: "Voulez-vous lancer Jupyter dans votre université, votre école ou votre enterprise?"
    form:
      name:
        en: "Your name"
        fr: "Votre nom"
      email:
        en: "Your email"
        fr: "Votre adresse courriel"
      message:
        en: "Your message"
        fr: "Votre message"
      button:
        en: "Send"
        fr: "Envoyer"
  about:
    what:
      en: 'What is Jupyter?'
      fr: "Qu'est-ce que Jupyter?"
      items:
        - text:
            en: 'Interactive computing environment'
            fr: 'Un environnement informatique interactif'
          class: 'fa fa-book'
        - text:
            en: 'Research tools accessed via browser'
            fr: 'Des outils de recherche accessibles dans un navigateur'
          class: 'fa fa-cloud'
        - text:
            en: 'Julia, Python, R'
            fr: 'Julia, Python, R'
          class: 'fa fa-flask'
    where:
      en: 'Where? How? Why?'
      fr: 'Où? Comment? Pourquoi?'
      items:
        - text:
            en: 'Hosted by Compute Canada and Cybera'
            fr: 'Hébergé par Calcul Canada et Cybera'
          class: 'fa fa-cogs'
        - text:
            en: 'Integrated with your single-sign-on system'
            fr: "Intégré à votre systéme d'authentifacation unique"
          class: 'fa fa-university'
        - text:
            en: 'Built for collaboration'
            fr: 'Conçu pour la collaboration'
          class: 'fa fa-users'
  service:
    title:
      en: 'Code, Analyze, Collaborate, Discover'
      fr: 'Coder, Analyser, Collaborer, Découvrir'
    description:
      en: 'The Pacific Institute for the Mathematical Sciences, Compute Canada and Cybera are collaborating to deliver Jupyter to researchers, educators and innovators across Canada.'
      fr: 'Le Pacific Institute for the Mathematical Sciences, Calcul Canada et Cybera collaborent pour offrir Jupyter aux chercheurs, aux éducateurs et aux innovateurs à la grandeur du Canada.'
  partners:
    title:
      en: 'Your Solution Partners'
      fr: 'Partenaires de vos Solutions'
  solutions:
    en: 'Find Solutions'
    fr: 'Trouvez de solutions'
